"""
Parameterized Python port of the Aeolia history engine (Phases 1–5).

Designed for black-box parameter optimization: fast, no Godot process required.
Consumes a ``base_world`` dict (pre-generated by run_headless.gd) that supplies
arch geography, plateau-edge adjacency, and substrate data. Replaces all
hardcoded magic numbers in history_engine.gd with entries from a ``params``
dict, so an optimizer can tune them freely.

Pipeline
--------
Phase 1  Dijkstra dual-source wavefront  (fixed edge costs — tunes DF timing)
Phase 2  Σ2ⁿ contact redistribution      (fixed fractions — tunes era shape)
Phase 3  Status assignment                (parameterized)
Phase 4  Population model (5 eras)        (fully parameterized)
Phase 5  Final state construction         (derived)

Usage
-----
    from thin_sim import simulate, DEFAULT_PARAMS

    with open("worlds/seed_42.json") as f:
        base_world = json.load(f)

    result = simulate(base_world, DEFAULT_PARAMS)
    # result["states"], result["df_year"], result["epi_log"], ...

For optimization, import ``params.py`` for bounds and suggest_params helpers.
"""

from __future__ import annotations

import heapq
import math
import random
from typing import Optional

# ---------------------------------------------------------------------------
# Crop-distance helper — mirrors history_engine._crop_distance exactly
# ---------------------------------------------------------------------------

_TROPICAL  = frozenset({"paddi", "taro", "sago"})
_TEMPERATE = frozenset({"emmer", "papa"})


def _crop_distance(contactor: str, contacted: str) -> float:
    if contactor == contacted:
        return 0.2
    ct = contactor in _TROPICAL
    cd = contacted  in _TROPICAL
    ce = contactor in _TEMPERATE
    de = contacted  in _TEMPERATE
    if (ct and cd) or (ce and de):
        return 0.5
    if frozenset([contactor, contacted]) == frozenset(["paddi", "papa"]):
        return 1.0
    return 0.8


def _log2(x: float) -> float:
    return math.log2(x) if x > 0 else 0.0


# ---------------------------------------------------------------------------
# Edge cost function — mirrors history_engine._edge_cost exactly.
# Kept fixed (not parameterised) so Phase-1 graph topology is stable.
# To tune Dark Forest timing, adjust edge-cost multipliers in params.py
# and pass them into _edge_cost via an edge_cost_scale param.
# ---------------------------------------------------------------------------

_ERA_BOUNDS = (-500, -200)


def _base_era_cost(year: int, hops: int, power: str) -> int:
    is_lattice  = power == "lattice"
    is_garrison = is_lattice and hops <= 3
    if year < -500:
        if is_garrison: return 167
        if is_lattice:  return 12000
        if hops <= 1:   return 350
        if hops <= 2:   return 580
        if hops <= 3:   return 1060
        return 8000
    elif year < -200:
        if is_garrison: return 85
        if is_lattice:  return 350 if hops <= 5 else 700
        if hops <= 4:   return 125
        if hops <= 6:   return 145
        return 200
    else:
        return 61


def _edge_cost(year: int, hops: int, power: str) -> int:
    cost = _base_era_cost(year, hops, power)
    for b in _ERA_BOUNDS:
        if year < b < year + cost:
            alt = (b - year + 1) + _base_era_cost(b + 1, hops, power)
            if alt < cost:
                return alt
    return cost


# ---------------------------------------------------------------------------
# Phase 1: Dijkstra dual-source wavefront
# ---------------------------------------------------------------------------

def _dijkstra(N: int, adj: list[list[int]],
              reach_arch: int, lattice_arch: int) -> tuple:
    """
    Returns (claimed, arrival_yr, hop_count, df_year, df_arch, df_detector).
    claimed[i] = "reach" | "lattice" | None
    arrival_yr[i] = int (year BP, negative) | None
    """
    R_START = -5500
    L_START = -5000

    claimed    = [None] * N
    arrival_yr = [None] * N
    hop_count  = [0]    * N

    claimed[reach_arch]   = "reach"
    arrival_yr[reach_arch] = R_START
    claimed[lattice_arch]  = "lattice"
    arrival_yr[lattice_arch] = L_START

    # heap: (year, arch_idx, power, hops, from_arch)
    pq: list = []
    for nb in adj[reach_arch]:
        c = _edge_cost(R_START, 1, "reach")
        heapq.heappush(pq, (R_START + c, nb, "reach", 1, reach_arch))
    for nb in adj[lattice_arch]:
        c = _edge_cost(L_START, 1, "lattice")
        heapq.heappush(pq, (L_START + c, nb, "lattice", 1, lattice_arch))

    df_year = df_arch = df_detector = None

    while pq:
        year, idx, power, hops, from_arch = heapq.heappop(pq)

        if claimed[idx] is not None:
            if claimed[idx] != power and df_year is None:
                df_year = year; df_arch = idx; df_detector = power
            continue

        claimed[idx]    = power
        arrival_yr[idx] = year
        hop_count[idx]  = hops

        for nb in adj[idx]:
            if claimed[nb] is not None and claimed[nb] != power and df_year is None:
                df_year = year; df_arch = idx; df_detector = power

        for nb in adj[idx]:
            if claimed[nb] is None:
                c = _edge_cost(year, hops + 1, power)
                heapq.heappush(pq, (year + c, nb, power, hops + 1, idx))

    return claimed, arrival_yr, hop_count, df_year, df_arch, df_detector


# ---------------------------------------------------------------------------
# Phase 2: Σ2ⁿ contact redistribution
# ---------------------------------------------------------------------------

def _redistribute(N: int, claimed: list, arrival_yr: list,
                  reach_arch: int, lattice_arch: int,
                  df_year: Optional[int],
                  adj: list[list[int]]) -> tuple:
    """
    Remaps Dijkstra arrival order onto four era time windows so that
    discovery accelerates geometrically across eras.

    Returns (claimed_new, arrival_yr_new, df_year_new, df_arch_new, df_detector_new).
    Fractions (0.05/0.10/0.20/0.40) are fixed — they ARE the Σ2ⁿ design target.
    """
    contactable = [
        i for i in range(N)
        if claimed[i] is not None and i not in (reach_arch, lattice_arch)
    ]
    # Stable sort: index tiebreaker matches JS Array.sort stable behaviour.
    contactable.sort(key=lambda i: (arrival_yr[i], i))
    nc = len(contactable)

    serial_n     = max(1, round(nc * 0.05))
    colonial_n   = max(1, round(nc * 0.10))
    industrial_n = max(2, round(nc * 0.20))
    nuclear_n    = max(2, round(nc * 0.40))
    total_slots  = serial_n + colonial_n + industrial_n + nuclear_n

    arrival_yr = arrival_yr[:]          # copy
    claimed    = claimed[:]

    for k, i in enumerate(contactable):
        if k < serial_n:
            arrival_yr[i] = -5000 + round((k + 1) / (serial_n + 1) * 3000)
        elif k < serial_n + colonial_n:
            j = k - serial_n
            arrival_yr[i] = -2000 + round((j + 1) / (colonial_n + 1) * 1500)
        elif k < serial_n + colonial_n + industrial_n:
            j = k - serial_n - colonial_n
            arrival_yr[i] = -500 + round((j + 1) / (industrial_n + 1) * 300)
        elif k < total_slots:
            j   = k - serial_n - colonial_n - industrial_n
            off = abs(df_year) if df_year is not None else 200
            arrival_yr[i] = -200 + round((j + 1) / (nuclear_n + 1) * min(200, off - 200))
        else:
            # El Dorado — beyond Σ2ⁿ budget
            claimed[i]    = None
            arrival_yr[i] = None

    # Recompute DF after redistribution
    df_year = df_arch = df_detector = None
    for i in range(N):
        if claimed[i] is None:
            continue
        for nb in adj[i]:
            if claimed[nb] is not None and claimed[nb] != claimed[i]:
                yr = max(arrival_yr[i] or 0, arrival_yr[nb] or 0)
                if df_year is None or yr < df_year:
                    df_year = yr; df_arch = i; df_detector = claimed[i]

    # Null out post-DF claims
    for i in range(N):
        if arrival_yr[i] is not None and df_year is not None and arrival_yr[i] > df_year:
            claimed[i]    = None
            arrival_yr[i] = None

    return claimed, arrival_yr, df_year, df_arch, df_detector


# ---------------------------------------------------------------------------
# Default parameter values — match current history_engine.gd exactly.
# Documented against lore source and HISTORY_ENGINE_ANALYSIS.md section.
# ---------------------------------------------------------------------------

DEFAULT_PARAMS: dict = {
    # ── Phase 3: Status assignment ─────────────────────────────────────────
    # Hop limits controlling who becomes a colony vs client vs contacted.
    "reach_colony_hop_limit":       3,    # ≤ 3 hops → colony (Reach)
    "reach_client_hop_limit":       5,    # ≤ 5 hops → client (Reach)
    "lattice_garrison_hop_limit":   3,    # ≤ 3 hops → garrison (Lattice)
    "lattice_tributary_hop_limit":  5,    # ≤ 5 hops → tributary (Lattice)
    # Initial sovereignty/trade values at contact (HISTORY_ENGINE_ANALYSIS §11)
    "reach_colony_sovereignty":     0.15,
    "reach_colony_trade":           0.85,
    "reach_client_sovereignty":     0.55,
    "reach_client_trade":           0.60,
    "lattice_garrison_sovereignty": 0.30,
    "lattice_garrison_trade":       0.50,
    "lattice_tributary_sovereignty":0.60,
    "lattice_tributary_trade":      0.40,

    # ── Phase 4 / Era 1: Antiquity (−20,000 to −5,000 BP) ─────────────────
    # HISTORY_ENGINE_ANALYSIS §2: current growth 0.002 produces only 3–6%
    # differentiation over 15,000 years; recommended range 0.003–0.009.
    "antiquity_growth_rate":        0.002,  # base growth rate per potential unit
    "antiquity_periods":            30,     # compounding periods (~500yr each)
    # Lattice paddi bonus (DESIGN_SPEC §10a paddi 5.0 t/ha vs emmer 2.5)
    "lattice_antiquity_pop_mult":   2.5,
    # Tech initialisation: potential × Uniform(tech_init_low, tech_init_low + 1.5)
    "tech_init_low":                2.5,
    "reach_tech_floor":             3.5,    # minimum starting tech for Reach
    "lattice_tech_floor":           3.8,    # minimum starting tech for Lattice

    # ── Phase 4 / Era 2: Serial contact (−5,000 to −2,000 BP) ────────────
    # Epidemiological shock — HISTORY_ENGINE_ANALYSIS §3 (highest priority)
    # base_severity drawn from Uniform(min, min + range), then scaled by crop_distance
    "shock_base_min":               0.20,   # 20% mortality at maximum crop distance
    "shock_base_range":             0.25,   # stochastic range above minimum
    # Trade recovery
    "trade_recovery_rate":          0.0004, # pop growth per year on network
    # Reach network effect (HISTORY_ENGINE_ANALYSIS §5 — corrected direction)
    # Reach A₀=1.2, δ=0.08: higher log₂ coefficient (knowledge compounds faster)
    "reach_serial_pop_base":        1.3,
    "reach_serial_log_coeff":       0.30,
    "reach_serial_tech_bonus":      1.2,
    # Lattice: large paddi base, lower scaling (stable surplus, not growing)
    "lattice_serial_pop_base":      1.9,
    "lattice_serial_log_coeff":     0.12,
    "lattice_serial_tech_bonus":    1.0,
    "serial_tech_ceiling":          6.0,    # min(tech, ceiling) after serial bonuses

    # ── Phase 4 / Era 3: Colonial empires (−2,000 to −500 BP) ─────────────
    "extraction_base_rate":         0.15,   # initial extraction fraction
    "extraction_growth_per_year":   0.0001, # rate increase per year of colonisation
    "garrison_absorption_min":      0.15,   # minimum fraction absorbed into Lattice core
    "garrison_absorption_range":    0.10,
    "tributary_tribute_min":        0.05,
    "tributary_tribute_range":      0.05,
    "settler_immigration_min":      8.0,    # absolute settler flow (not percentage)
    "settler_immigration_range":    15.0,
    "reach_colonies_pop_coeff":     0.12,   # pop[reach] *= 1 + n_colonies × coeff
    "extracted_transit_eff":        0.6,    # fraction of extracted goods reaching metropole
    "lattice_garrisons_pop_coeff":  0.15,
    "lattice_tribs_pop_coeff":      0.08,

    # ── Phase 4 / Era 4: Industrial (−500 to −200 BP) ─────────────────────
    # HISTORY_ENGINE_ANALYSIS §8 — corrected to match Solow-Romer A₀/δ differentials
    # Reach A₀=1.2, δ=0.08: higher tech leverage AND knowledge compounding
    "reach_ind_tech_coeff":         0.12,
    "reach_ind_resource_coeff":     0.14,
    "reach_ind_log_coeff":          0.14,
    "reach_ind_tech_growth":        0.9,
    # Lattice A₀=0.8, β=0.6: lower tech leverage, higher resource leverage
    "lattice_ind_tech_coeff":       0.06,
    "lattice_ind_resource_coeff":   0.22,
    "lattice_ind_log_coeff":        0.10,
    "lattice_ind_tech_growth":      0.6,
    # Free/independent contacts (sovereignty > 0, not a colony)
    "free_tech_coeff":              0.08,
    "free_resource_coeff":          0.12,
    "free_tech_growth":             0.7,    # potential × coeff added to tech
    # Colonies (sovereign >= 0)
    "colony_tech_coeff":            0.03,
    "colony_resource_coeff":        0.05,
    "colony_tech_growth":           0.3,
    # Hard floors (HISTORY_ENGINE_ANALYSIS §9 — soft variant)
    "reach_ind_tech_floor":         7.0,
    "lattice_ind_tech_floor":       6.5,

    # ── Phase 4 / Era 4→5 sovereignty drift ───────────────────────────────
    "colony_sov_drift_coeff":       0.3,     # sovereignty += extraction_rate × coeff
    "client_sov_drift_rate":        0.00005, # sovereignty += contact_age × rate

    # ── Phase 4 / Era 5: Nuclear (−200 BP to present) ─────────────────────
    "reach_nuclear_pop_mult":       1.4,
    "lattice_nuclear_pop_mult":     1.35,
    # Tech is fixed at 10.0/9.5 to match narrative (freeing it adds 2 dimensions
    # but makes independent-power detection harder — see HISTORY_ENGINE_ANALYSIS §9)
    "nuclear_access_colony":        0.7,    # former Reach colonies: deep trade integration
    "nuclear_access_garrison":      0.5,    # former Lattice garrisons: institutional transfer
    "nuclear_access_contact":       0.3,    # independent contacts: selective adoption
    "green_revolution_prob":        0.4,
    "green_revolution_mult_min":    1.3,
    "green_revolution_mult_range":  0.3,
    "nuclear_pop_coeff":            0.2,    # pop *= 1 + access × coeff

    # ── Post-nuclear sovereignty recovery ─────────────────────────────────
    "colony_nuclear_sov_recovery":  0.35,
    "colony_nuclear_trade_decay":   0.85,
    "garrison_nuclear_sov_recovery":0.20,
}


# ---------------------------------------------------------------------------
# Main simulation entry point
# ---------------------------------------------------------------------------

def simulate(base_world: dict,
             params: Optional[dict] = None,
             rng_seed: Optional[int] = None) -> dict:
    """
    Run the full parameterised simulation pipeline.

    Parameters
    ----------
    base_world : dict
        Output of run_headless.gd. Required keys:
            n, reach_arch, lattice_arch,
            archs (list of {lat, size, shelf_r, peak_count, potential}),
            adj  (adjacency list — list of lists of ints),
            substrate (list of {primary_crop} per arch),
            names (list of str)
        Optional: seed

    params : dict | None
        Parameter overrides. Any key absent falls back to DEFAULT_PARAMS.

    rng_seed : int | None
        RNG seed for stochastic elements. Defaults to base_world["seed"].
        Use different seeds to average over stochastic variance.

    Returns
    -------
    dict with keys:
        states        list[dict]  — per-arch final state
        df_year       int | None
        df_arch       int | None
        df_detector   str | None
        epi_log       list[dict]  — structured epidemic records for epi_component()
        reach_arch    int
        lattice_arch  int
        n             int
        archs         list[dict]
        substrate     list[dict]
        names         list[str]
        seed          int
    """
    p = {**DEFAULT_PARAMS, **(params or {})}
    N            = base_world["n"]
    reach_arch   = base_world["reach_arch"]
    lattice_arch = base_world["lattice_arch"]
    archs        = base_world["archs"]
    adj          = base_world["adj"]
    substrate    = base_world.get("substrate", [{}] * N)
    names        = base_world.get("names", [f"Arch {i}" for i in range(N)])
    seed         = rng_seed if rng_seed is not None else base_world.get("seed", 42)

    rng = random.Random(seed)

    def rnd() -> float:
        return rng.random()

    potential = [a["potential"] for a in archs]

    # ── Phase 1: Dijkstra ────────────────────────────────────────────────
    claimed, arrival_yr, hop_count, df_year, df_arch, df_detector = \
        _dijkstra(N, adj, reach_arch, lattice_arch)

    # ── Phase 2: Σ2ⁿ redistribution ─────────────────────────────────────
    claimed, arrival_yr, df_year, df_arch, df_detector = \
        _redistribute(N, claimed, arrival_yr, reach_arch, lattice_arch,
                      df_year, adj)

    # ── Phase 3: Status assignment ───────────────────────────────────────
    sovereign  = [-1] * N   # index of sovereign arch, -1 = none
    colony_yr  = [None] * N
    status_data = [
        {"sovereignty": 1.0, "tradeIntegration": 0.0,
         "status": "uncontacted", "eraOfContact": None}
        for _ in range(N)
    ]

    for i in range(N):
        if i == reach_arch or i == lattice_arch:
            status_data[i] = {
                "sovereignty": 1.0, "tradeIntegration": 1.0,
                "status": "core", "eraOfContact": None,
            }
            continue

        yr    = arrival_yr[i]
        power = claimed[i]
        hops  = hop_count[i]
        if yr is None or power is None:
            continue

        era = ("sail"       if yr < -2000 else
               "colonial"   if yr < -500  else
               "industrial" if yr < -200  else "nuclear")
        status_data[i]["eraOfContact"] = era

        if power == "reach":
            if hops <= p["reach_colony_hop_limit"] and era != "nuclear":
                sovereign[i] = reach_arch
                colony_yr[i] = yr + int(100 + rnd() * 300)
                status_data[i] = {
                    "sovereignty":       p["reach_colony_sovereignty"],
                    "tradeIntegration":  p["reach_colony_trade"],
                    "status": "colony",  "eraOfContact": era,
                }
            elif hops <= p["reach_client_hop_limit"] and era != "nuclear":
                status_data[i] = {
                    "sovereignty":      p["reach_client_sovereignty"],
                    "tradeIntegration": p["reach_client_trade"],
                    "status": "client", "eraOfContact": era,
                }
            else:
                status_data[i] = {
                    "sovereignty": 0.90, "tradeIntegration": 0.20,
                    "status": "contacted", "eraOfContact": era,
                }
        else:  # lattice
            if hops <= p["lattice_garrison_hop_limit"]:
                sovereign[i] = lattice_arch
                colony_yr[i] = yr + 200
                status_data[i] = {
                    "sovereignty":      p["lattice_garrison_sovereignty"],
                    "tradeIntegration": p["lattice_garrison_trade"],
                    "status": "garrison", "eraOfContact": era,
                }
            elif hops <= p["lattice_tributary_hop_limit"]:
                status_data[i] = {
                    "sovereignty":      p["lattice_tributary_sovereignty"],
                    "tradeIntegration": p["lattice_tributary_trade"],
                    "status": "tributary", "eraOfContact": era,
                }
            else:
                status_data[i] = {
                    "sovereignty": 0.90, "tradeIntegration": 0.15,
                    "status": "pulse", "eraOfContact": era,
                }

    # ── Phase 4: Population model ─────────────────────────────────────────

    pop  = [float(a["peak_count"]) * a["size"] * (3.0 + rnd() * 4.0) for a in archs]
    tech = [0.0] * N

    epi_log: list[dict] = []  # structured epidemic records for epi_component()

    # ── ERA 1: ANTIQUITY ─────────────────────────────────────────────────
    rate    = p["antiquity_growth_rate"]
    periods = p["antiquity_periods"]
    for i in range(N):
        pop[i]  *= (1.0 + rate * potential[i]) ** periods
        tech[i]  = potential[i] * (p["tech_init_low"] + rnd() * 1.5)

    tech[reach_arch]   = max(tech[reach_arch],   p["reach_tech_floor"])
    tech[lattice_arch] = max(tech[lattice_arch],  p["lattice_tech_floor"])
    pop[lattice_arch] *= p["lattice_antiquity_pop_mult"]

    # ── ERA 2: SERIAL CONTACT ─────────────────────────────────────────────
    reach_network   = 0
    lattice_network = 0

    for i in range(N):
        if i in (reach_arch, lattice_arch):
            continue
        yr    = arrival_yr[i]
        power = claimed[i]
        if yr is not None and -5000 <= yr < -2000:
            c_crop = "emmer" if power == "reach" else "paddi"
            t_crop = substrate[i].get("primary_crop", "emmer") if i < len(substrate) else "emmer"
            dist   = _crop_distance(c_crop, t_crop)
            base_s = p["shock_base_min"] + rnd() * p["shock_base_range"]
            shock  = 1.0 - base_s * dist
            pop[i] *= shock
            epi_log.append({
                "arch": i, "era": "sail",
                "contactor_crop": c_crop, "contacted_crop": t_crop,
                "crop_distance": dist,
                "mortality_rate": 1.0 - shock,
            })
            trade_years = max(0, -2000 - yr)
            pop[i] *= 1.0 + float(trade_years) * p["trade_recovery_rate"]
            tech[i] += 0.5 + rnd() * 0.5
            if power == "reach":
                reach_network   += 1
            else:
                lattice_network += 1
        elif yr is None or yr >= -2000:
            pop[i] *= 1.0 + 0.001 * potential[i] * 30.0

    # Reach: higher log₂ coefficient (A₀=1.2, δ=0.08)
    pop[reach_arch] *= (
        p["reach_serial_pop_base"] *
        (1.0 + _log2(1.0 + reach_network) * p["reach_serial_log_coeff"])
    )
    tech[reach_arch] = min(p["serial_tech_ceiling"],
                           tech[reach_arch] + p["reach_serial_tech_bonus"])

    # Lattice: larger base (paddi surplus), lower log₂ coefficient
    pop[lattice_arch] *= (
        p["lattice_serial_pop_base"] *
        (1.0 + _log2(1.0 + lattice_network) * p["lattice_serial_log_coeff"])
    )
    tech[lattice_arch] = min(p["serial_tech_ceiling"],
                             tech[lattice_arch] + p["lattice_serial_tech_bonus"])

    # ── ERA 3: COLONIAL EMPIRES ───────────────────────────────────────────
    reach_colonies  = 0
    lattice_garrisons = 0
    lattice_tribs   = 0
    total_extracted = 0.0
    total_enslaved  = 0.0
    extraction_rate_for = [0.0] * N

    for i in range(N):
        if i in (reach_arch, lattice_arch):
            continue
        yr    = arrival_yr[i]
        power = claimed[i]
        sd    = status_data[i]
        if yr is None:
            continue

        if yr < -500:
            if sd["status"] == "colony":
                col_start = colony_yr[i] if colony_yr[i] is not None else yr
                col_years = max(0, -500 - col_start)
                extr = min(0.30,
                           p["extraction_base_rate"] +
                           col_years * p["extraction_growth_per_year"])
                extraction_rate_for[i] = extr
                extracted = pop[i] * extr
                pop[i]   -= extracted
                total_extracted += extracted
                enslaved  = pop[i] * (0.05 + rnd() * 0.10)
                pop[i]   -= enslaved
                total_enslaved += enslaved
                pop[i]   += (p["settler_immigration_min"] +
                              rnd() * p["settler_immigration_range"])
                reach_colonies += 1

            elif sd["status"] == "garrison":
                abs_r    = p["garrison_absorption_min"] + rnd() * p["garrison_absorption_range"]
                absorbed = pop[i] * abs_r
                pop[i]  -= absorbed
                pop[lattice_arch] += absorbed
                lattice_garrisons += 1

            elif sd["status"] == "tributary":
                trib_r  = p["tributary_tribute_min"] + rnd() * p["tributary_tribute_range"]
                tribute = pop[i] * trib_r
                pop[lattice_arch] += tribute
                lattice_tribs += 1

            elif sd["status"] == "client":
                pop[i]  *= 1.0 + _log2(1.0 + reach_network) * 0.10
                tech[i] += 0.3 + rnd() * 0.3

        if yr is not None and -2000 <= yr < -500:
            c_crop = "emmer" if power == "reach" else "paddi"
            t_crop = substrate[i].get("primary_crop", "emmer") if i < len(substrate) else "emmer"
            dist   = _crop_distance(c_crop, t_crop)
            base_s = p["shock_base_min"] + rnd() * p["shock_base_range"]
            shock  = 1.0 - base_s * dist
            pop[i] *= shock
            epi_log.append({
                "arch": i, "era": "colonial",
                "contactor_crop": c_crop, "contacted_crop": t_crop,
                "crop_distance": dist,
                "mortality_rate": 1.0 - shock,
            })
            tech[i] += 0.3
            if power == "reach":
                reach_network   += 1
            elif power == "lattice":
                lattice_network += 1

    pop[reach_arch]   *= 1.0 + reach_colonies * p["reach_colonies_pop_coeff"]
    pop[reach_arch]   += total_extracted * p["extracted_transit_eff"] + total_enslaved
    lattice_integrated = lattice_garrisons + lattice_tribs
    pop[lattice_arch] *= (1.0
                          + lattice_garrisons * p["lattice_garrisons_pop_coeff"]
                          + lattice_tribs     * p["lattice_tribs_pop_coeff"])

    for i in range(N):
        if claimed[i] is not None or i in (reach_arch, lattice_arch):
            continue
        pop[i]  *= 1.0 + 0.0005 * potential[i] * 15.0
        tech[i]  = min(4.0, tech[i] + potential[i] * 0.1)

    # ── ERA 4: INDUSTRIAL ─────────────────────────────────────────────────
    total_network = reach_network + lattice_network

    for i in range(N):
        if i == reach_arch:
            pop[i] *= ((1.0 + tech[i] * p["reach_ind_tech_coeff"]
                             + potential[i] * p["reach_ind_resource_coeff"]) *
                        (1.0 + _log2(1.0 + total_network) * p["reach_ind_log_coeff"]))
            tech[i] = min(8.0, tech[i] + potential[i] * p["reach_ind_tech_growth"])
            continue

        if i == lattice_arch:
            pop[i] *= ((1.0 + tech[i] * p["lattice_ind_tech_coeff"]
                             + potential[i] * p["lattice_ind_resource_coeff"]) *
                        (1.0 + _log2(1.0 + lattice_integrated) * p["lattice_ind_log_coeff"]))
            tech[i] = min(8.0, tech[i] + potential[i] * p["lattice_ind_tech_growth"])
            continue

        if claimed[i] is None:
            pop[i]  *= 1.0 + 0.0003 * potential[i] * 6.0
            tech[i]  = min(4.5, tech[i] + potential[i] * 0.05)
            continue

        if sovereign[i] >= 0:  # colony / garrison
            pop[i]  *= (1.0 + tech[i] * p["colony_tech_coeff"]
                             + potential[i] * p["colony_resource_coeff"])
            tech[i]  = min(6.0, tech[i] + potential[i] * p["colony_tech_growth"])
        else:
            pop[i]  *= (1.0 + tech[i] * p["free_tech_coeff"]
                             + potential[i] * p["free_resource_coeff"])
            tech[i]  = min(7.5, tech[i] + potential[i] * p["free_tech_growth"])

        yr = arrival_yr[i]
        if yr is not None and -500 <= yr < -200:
            pop[i] *= 0.5 + rnd() * 0.3

    tech[reach_arch]   = max(tech[reach_arch],   p["reach_ind_tech_floor"])
    tech[lattice_arch] = max(tech[lattice_arch],  p["lattice_ind_tech_floor"])

    # ── ERA 4→5 TRANSITION: sovereignty drift ────────────────────────────
    for i in range(N):
        if claimed[i] is None or i in (reach_arch, lattice_arch):
            continue
        sd = status_data[i]
        if sd["status"] == "colony":
            sd["sovereignty"] = min(0.45,
                sd["sovereignty"] + extraction_rate_for[i] * p["colony_sov_drift_coeff"])
        elif sd["status"] == "client":
            age = max(0, -500 - (arrival_yr[i] or -500))
            sd["sovereignty"] = min(0.80,
                sd["sovereignty"] + float(age) * p["client_sov_drift_rate"])

    # ── ERA 5: NUCLEAR ────────────────────────────────────────────────────
    pop[reach_arch]   *= p["reach_nuclear_pop_mult"]
    tech[reach_arch]   = 10.0              # fixed to match lore end-state
    pop[lattice_arch] *= p["lattice_nuclear_pop_mult"]
    tech[lattice_arch] = 9.5

    for i in range(N):
        if i in (reach_arch, lattice_arch) or claimed[i] is None:
            continue

        if sovereign[i] == reach_arch:
            access = p["nuclear_access_colony"]
        elif sovereign[i] == lattice_arch:
            access = p["nuclear_access_garrison"]
        else:
            access = p["nuclear_access_contact"]

        if sovereign[i] >= 0 and rnd() < p["green_revolution_prob"]:
            pop[i] *= (p["green_revolution_mult_min"] +
                       rnd() * p["green_revolution_mult_range"])

        pop[i]  *= 1.0 + access * p["nuclear_pop_coeff"]
        tech[i]  = min(10.0, tech[i] + access)

    # ── Post-nuclear sovereignty recovery ─────────────────────────────────
    for i in range(N):
        if claimed[i] is None or i in (reach_arch, lattice_arch):
            continue
        sd = status_data[i]
        if sd["status"] == "colony":
            sd["sovereignty"]      = min(0.75,
                sd["sovereignty"] + p["colony_nuclear_sov_recovery"])
            sd["tradeIntegration"] *= p["colony_nuclear_trade_decay"]
        elif sd["status"] == "garrison":
            sd["sovereignty"]      = min(0.65,
                sd["sovereignty"] + p["garrison_nuclear_sov_recovery"])

    # ── Phase 5: Final states ─────────────────────────────────────────────
    max_pop = max(pop) if pop else 1.0

    states: list[dict] = []
    for i in range(N):
        sd = status_data[i]
        if i == reach_arch:
            faction = "reach"
        elif i == lattice_arch:
            faction = "lattice"
        elif claimed[i] is None:
            faction = "unknown"
        else:
            faction = claimed[i]

        states.append({
            "faction":          faction,
            "status":           sd["status"],
            "name":             names[i] if i < len(names) else f"Arch {i}",
            "population":       round(pop[i]),
            "tech":             round(tech[i] * 10) / 10.0,
            "sovereignty":      sd["sovereignty"],
            "tradeIntegration": sd["tradeIntegration"],
            "eraOfContact":     sd["eraOfContact"],
            "hopCount":         hop_count[i],
            "urbanization":     pop[i] / max_pop,
        })

    return {
        "states":       states,
        "df_year":      df_year,
        "df_arch":      df_arch,
        "df_detector":  df_detector,
        "epi_log":      epi_log,
        "reach_arch":   reach_arch,
        "lattice_arch": lattice_arch,
        "n":            N,
        "archs":        archs,
        "substrate":    substrate,
        "names":        names,
        "seed":         seed,
    }


# ---------------------------------------------------------------------------
# Smoke test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import json, sys

    if len(sys.argv) < 2:
        print("Usage: python thin_sim.py base_world.json [params_override.json]")
        sys.exit(1)

    with open(sys.argv[1]) as f:
        base_world = json.load(f)

    params = None
    if len(sys.argv) >= 3:
        with open(sys.argv[2]) as f:
            params = json.load(f)

    result = simulate(base_world, params)
    s = result["states"]
    ra = result["reach_arch"]
    la = result["lattice_arch"]
    print(f"Seed {result['seed']}  N={result['n']}")
    print(f"  Reach   tech={s[ra]['tech']}  pop={s[ra]['population']:,}")
    print(f"  Lattice tech={s[la]['tech']}  pop={s[la]['population']:,}")
    print(f"  pop ratio L/R = {s[la]['population'] / max(s[ra]['population'], 1):.2f}")
    print(f"  DF year = {result['df_year']}")
    print(f"  epi contacts = {len(result['epi_log'])}")
    n_indep = sum(
        1 for st in s
        if st["status"] in {"contacted", "client", "pulse"}
        and st["tech"] > 6.0 and st["sovereignty"] > 0.7
    )
    print(f"  independent powers (tech>6, sov>0.7) = {n_indep}")
